services:
  laravel.test:
    image: 'sail-8.4/app'
    build:
      context: './vendor/laravel/sail/runtimes/8.4'
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    depends_on:
      - mailpit
      - mysql
      - valkey
    volumes:
      - .:/var/www/html
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    networks:
      - sail
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
    networks:
      - sail
  mysql:
    image: 'mysql/mysql-server:8.0'
    volumes:
      - mysql:/var/lib/mysql
      - ./vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
  valkey:
    image: 'valkey/valkey:alpine'
    volumes:
      - valkey:/data
    ports:
      - '${FORWARD_VALKEY_PORT:-6379}:6379'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - valkey-cli
        - ping
      retries: 3
      timeout: 5s
networks:
  sail:
    driver: bridge
volumes:
  mysql:
    driver: local
  valkey:
    driver: local
